/**
 * HealthPlus — deterministic Tier 4 confidence and disclosure policy.
 *
 * Charter §1.0.5: "Confidence MUST NOT be generated by the language model.
 * It is computed by the Data Quality Engine from tier + modifiers and passed
 * to the model as read-only context. A model-authored number in a confidence
 * field is a defect." This module is that computation for provider-submitted
 * (Tier 4) claims — code and lookups only, never a model call, matching the
 * `evidence.claim_source` constraint `conf_not_llm CHECK (computed_by <> 'MODEL')`.
 *
 * Source: Evidence & Safety Charter v1.0 §1.4 (Tier 4 — hospital and
 * provider information).
 */

export type ClaimKind =
  | 'GENERAL_EDUCATION'
  | 'CLINICAL_EFFICACY'
  | 'TEST_INTERPRETATION'
  | 'REFERENCE_RANGE'
  | 'ELIGIBILITY'
  | 'COST'
  | 'PROVIDER_OUTCOME'
  | 'PROVIDER_CREDENTIAL'
  | 'GUIDELINE'
  | 'LEGAL_REGULATORY'
  | 'LOGISTICS'
  | 'SENTIMENT';

/** The claim_kind values this extraction job is scoped to produce from a
 *  partner-portal submission (domain.provider_submission.payload). Anything
 *  else found in a payload is out of scope for this job and is left
 *  unextracted rather than guessed at. */
export const PROVIDER_SUBMISSION_CLAIM_KINDS = [
  'COST',
  'PROVIDER_OUTCOME',
  'PROVIDER_CREDENTIAL',
  'LOGISTICS',
] as const satisfies readonly ClaimKind[];

export type ProviderSubmissionClaimKind = (typeof PROVIDER_SUBMISSION_CLAIM_KINDS)[number];

/** §1.4.3 default confidence for a Tier 4 source. */
export const TIER_4_DEFAULT_CONFIDENCE = 0.55;

/** §1.4.3: ceiling applies only to administratively verifiable facts
 *  (address, licence number, listed price, published contact details,
 *  spoken languages, opening hours). */
export const TIER_4_ADMIN_VERIFIABLE_CEILING = 0.75;

/** §1.4.4: hard ceiling on clinical outcome / success-rate / comparative-
 *  superiority claims. Below this a claim MUST NOT be presented as fact and
 *  MUST carry the mandatory self-report marker string. */
export const TIER_4_CLINICAL_CLAIM_CAP = 0.4;

/** §1.4.4's mandatory string. Not a stylistic option — must be attached
 *  verbatim to every provider-asserted clinical/outcome claim. */
export const SELF_REPORT_MARKER =
  'Reported by the hospital; not independently verified.';

/** §1.4.4: which of this job's in-scope claim kinds are the "clinical
 *  outcome, success rate, complication rate, survival, patient volume,
 *  comparative superiority, or world-class/best/leading positioning" class
 *  that must be capped at 0.40 and carry the self-report marker.
 *  PROVIDER_CREDENTIAL is included here ONLY for accreditation-style
 *  assertions (see `isAccreditationCredential`); registration numbers,
 *  languages spoken, and similar administrative facts are not. */
const CLINICAL_CAP_KINDS = new Set<ProviderSubmissionClaimKind>(['PROVIDER_OUTCOME']);

/** §1.4.6 / §1.7.1: COST claims decay fastest of anything this job handles
 *  and MUST carry an expires_at (`evidence.claim` CHECK cost_expiry). Actual
 *  half-life/hard-expiry numbers are NOT hard-coded here — they are read
 *  live from `evidence.claim_kind_decay` at extraction time (see
 *  extractClaimsFromProviderSubmission.ts), because AMB-07 records those
 *  numbers as a Board-owned business decision that must be changeable by a
 *  single DB row, not a code deploy. This module only decides *whether* a
 *  kind requires an expiry to be resolved before the claim can be inserted.
 */
export const KINDS_REQUIRING_EXPIRY = new Set<ProviderSubmissionClaimKind>(['COST']);

export interface AccreditationCredentialInput {
  kind: ProviderSubmissionClaimKind;
  /** true when the extracted statement asserts an accreditation/certification
   *  status (JCI, NABH, ISO, "centre of excellence", etc.) rather than a
   *  plain administrative fact (registration number, address, hours). */
  isAccreditationAssertion: boolean;
}

/** §1.2.6 / §3.4.3: a provider's own accreditation claim is Tier 4 and MUST
 *  NOT be published as verified until matched against the accreditor's own
 *  directory — this job does no such matching, so it treats an accreditation
 *  assertion the same as a clinical/outcome claim: capped, marked, never
 *  presented as fact. */
export function requiresClinicalCapAndMarker(input: AccreditationCredentialInput): boolean {
  if (CLINICAL_CAP_KINDS.has(input.kind)) return true;
  if (input.kind === 'PROVIDER_CREDENTIAL' && input.isAccreditationAssertion) return true;
  return false;
}

/**
 * Deterministic Tier 4 confidence for a validated candidate claim.
 * NEVER call this with a model-supplied number — the whole point of §1.0.5
 * is that this function, not the LLM, is the confidence authority.
 */
export function computeTier4Confidence(input: AccreditationCredentialInput): number {
  if (requiresClinicalCapAndMarker(input)) {
    return TIER_4_CLINICAL_CLAIM_CAP;
  }
  // COST (listed price) and administrative LOGISTICS/PROVIDER_CREDENTIAL facts
  // sit at the §1.4.3 default. They are permitted up to the 0.75 ceiling by
  // later corroboration (M3) or other modifiers — this job does not apply
  // modifiers, it only establishes the base Tier 4 confidence at ingest time.
  return TIER_4_DEFAULT_CONFIDENCE;
}

export function confidenceSourceFor(kind: ProviderSubmissionClaimKind): string {
  return `TIER4_INLINE_POLICY_V1:${kind}`;
}
