import { createHmac, createHash } from 'node:crypto';

/**
 * ADR-003 §2.3 / HP-RB-001 §3: the immutable trace never carries a raw
 * subject_id. subject_pseudonym = HMAC(user_id, subject_key.salt).
 *
 * ---------------------------------------------------------------------------
 * WHAT CHANGED, AND WHY THE SALT IS NOW A PARAMETER
 *
 * This module used to derive its HMAC key from SUBJECT_HMAC_KEY, a single
 * process-wide secret, and its own comment said what that was: "a stand-in for
 * the per-subject `subject_key` table … swap this for a real per-key lookup
 * before this goes near production data." The lookup did not exist because the
 * table had no mint (HP-RECON-006 §3); migration 038 built the mint and 039 the
 * read verb, so the stand-in is now removable and is removed. There is no
 * fallback: a caller without a salt cannot compute a pseudonym at all, which is
 * the point — a fallback would silently reinstate the process-wide key for
 * exactly the subjects whose key lookup failed.
 *
 * ONE SALT PER SUBJECT IS WHAT MAKES ERASURE WORK. principal.erase_subject nulls
 * the salt and sets destroyed_at, and after that HMAC(user_id, salt) is not
 * recomputable by anyone, including us. That is precisely why HP-LB-001's
 * audit-vs-erasure reconciliation can leave obs.response_audit standing: the
 * rows survive, and the link from them back to a person does not. Under a
 * process-wide key erasure would have deleted nothing — every pseudonym stays
 * recomputable from a user_id and one env var.
 *
 * SESSION PSEUDONYMS ARE SALTED WITH THE *SUBJECT'S* SALT, deliberately. A
 * session belongs to exactly one subject, so nothing is lost, and two things are
 * gained: a session pseudonym cannot be computed without holding that subject's
 * key material, and erasure severs the session linkage in the same stroke as the
 * subject linkage. The cost is real and belongs here rather than in a surprise:
 * safety.session_severity_floor rows for an erased subject become unreachable —
 * no key, no pseudonym, no lookup — and clearSessionSeverityFloor therefore
 * needs the subject's salt, not just a session id. §4.0.8's unbuilt clinician
 * tool must resolve the subject before it can clear a floor.
 */

/**
 * @param salt principal.subject_key.salt — 32 bytes, generated by the database
 *   in migration 038 and fetched through principal.subject_key_material.
 */
export function subjectPseudonym(userId: string, salt: Buffer): Buffer {
  return createHmac('sha256', requireSalt(salt)).update(userId).digest();
}

export function sessionPseudonym(sessionId: string, salt: Buffer): Buffer {
  return createHmac('sha256', requireSalt(salt)).update(sessionId).digest();
}

/**
 * An empty or short salt is not a degraded pseudonym, it is a DIFFERENT
 * pseudonym namespace — and one that would be written into the audit trail
 * looking exactly like a real one. Caught here rather than at the point someone
 * later tries to reconcile two rows that should have matched.
 */
function requireSalt(salt: Buffer): Buffer {
  if (!salt || salt.length < 32) {
    throw new Error(
      `pseudonymize: subject salt is ${salt ? `${salt.length} bytes` : 'missing'}; ` +
        'expected the 32 bytes principal.subject_key.salt holds. Resolve it once per ' +
        'request with getOrMintSubjectKey and carry it on PipelineContext.',
    );
  }
  return salt;
}

/**
 * §3.13.1 fabrication_block.query_hash / RB-001 payload_no_pii: hash the
 * user's message, never store or log the plaintext in an audit-adjacent
 * table.
 *
 * UNSALTED, and that is a decision rather than an oversight. query_hash exists
 * so two blocks on the same question can be recognised as the same question
 * ACROSS subjects — that is what makes it useful for spotting a prohibition
 * class firing on one phrasing. Salting it per subject would destroy that and
 * buy little: the input space of health questions is small enough that a salted
 * hash is not meaningfully less guessable than an unsalted one.
 */
export function queryHash(message: string): Buffer {
  return createHash('sha256').update(message, 'utf8').digest();
}
