import { randomBytes, createCipheriv, createDecipheriv } from 'node:crypto';
import { inspect } from 'node:util';
import type { PoolClient } from 'pg';
import { db } from './db';

/**
 * The per-subject key, ADR-003 §2.4's crypto-shredding unit.
 *
 * WHAT THIS REPLACES. `persistResponseContent` used to derive its AES key from
 * SUBJECT_HMAC_KEY and pass `key_id: null`, with its own comment saying so:
 * "a working placeholder … do not ship this derivation as the production key
 * path." Against the real schema that write is impossible anyway —
 * obs.response_content.key_id is NOT NULL with an FK to principal.subject_key —
 * and until migration 038 there was no way to create a row in that table at all.
 *
 * THE SPLIT. The database owns the salt and generates it (migration 038); the
 * application owns the wrapping key and therefore the DEK. So:
 *
 *   principal.ensure_subject_key(subject, wrapped_dek)  mint, idempotent
 *   principal.subject_key_material(subject)             read, live keys only
 *
 * Both are SECURITY DEFINER. principal.subject_key itself is unreachable to
 * every application role — hp_app holds no table privilege on it — so the
 * request path can create and use a key without being able to read one
 * directly, alter one, or clear a destroyed_at.
 *
 * WHAT THE DESIGN ACTUALLY BUYS, stated plainly because "the app can unwrap
 * every DEK" reads alarming out of context: the DATABASE never holds the
 * wrapping key. A dump, a replica, a backup tape or a compromised read-only
 * role yields ciphertext and wrapped keys and nothing else. The application
 * holding the wrapping key is not a weakness of the scheme, it is the scheme —
 * something has to encrypt. The real exposure is that SUBJECT_KEY_WRAPPING_KEY
 * is a single point of compromise, which migration 038 records and which
 * rotation (a re-wrap of every live row) addresses when there is something to
 * protect.
 *
 * AND ERASURE. principal.erase_subject nulls salt and wrapped_dek and sets
 * destroyed_at; subject_key_material returns ZERO ROWS thereafter — the same
 * answer as a subject who never existed. Everything encrypted under that DEK is
 * permanently unreadable, which is the whole mechanism, and
 * migrations/test/key_mint.sh §5 demonstrates it end to end rather than
 * asserting it.
 */

const WRAP_ALG = 'aes-256-gcm';
const DEK_BYTES = 32;   // AES-256
const NONCE_BYTES = 12; // GCM standard
const TAG_BYTES = 16;

/**
 * Accepts `base64:…` or `hex:…` or raw utf8, mirroring how SUBJECT_HMAC_KEY was
 * read, and REFUSES anything that is not exactly 32 bytes. A short key does not
 * fail at wrap time — Node pads or throws depending on the algorithm — so a
 * deployment with a truncated secret could otherwise encrypt everything under a
 * key nobody intended.
 */
function wrappingKey(): Buffer {
  const raw = process.env.SUBJECT_KEY_WRAPPING_KEY ?? '';
  if (!raw) {
    throw new Error(
      'SUBJECT_KEY_WRAPPING_KEY is not set. Every subject key is wrapped under it; ' +
        'without it the application cannot encrypt response content and must not start.',
    );
  }
  const key = raw.startsWith('base64:')
    ? Buffer.from(raw.slice('base64:'.length), 'base64')
    : raw.startsWith('hex:')
      ? Buffer.from(raw.slice('hex:'.length), 'hex')
      : Buffer.from(raw, 'utf8');
  if (key.length !== DEK_BYTES) {
    throw new Error(
      `SUBJECT_KEY_WRAPPING_KEY must be ${DEK_BYTES} bytes, got ${key.length}. ` +
        'Use base64: or hex: for binary material rather than a passphrase.',
    );
  }
  return key;
}

/** nonce | tag | ciphertext — 60 bytes for a 32-byte DEK. */
function wrap(dek: Buffer): Buffer {
  const nonce = randomBytes(NONCE_BYTES);
  const c = createCipheriv(WRAP_ALG, wrappingKey(), nonce);
  const ct = Buffer.concat([c.update(dek), c.final()]);
  return Buffer.concat([nonce, c.getAuthTag(), ct]);
}

function unwrap(wrapped: Buffer): Buffer {
  if (wrapped.length < NONCE_BYTES + TAG_BYTES + DEK_BYTES) {
    throw new Error(`subjectKey: wrapped DEK is ${wrapped.length} bytes, too short to be valid`);
  }
  const nonce = wrapped.subarray(0, NONCE_BYTES);
  const tag = wrapped.subarray(NONCE_BYTES, NONCE_BYTES + TAG_BYTES);
  const ct = wrapped.subarray(NONCE_BYTES + TAG_BYTES);
  const d = createDecipheriv(WRAP_ALG, wrappingKey(), nonce);
  d.setAuthTag(tag);
  // GCM authenticates: a wrong wrapping key throws here rather than returning
  // plausible-looking garbage, which is the difference between a loud
  // misconfiguration and silently unreadable data.
  return Buffer.concat([d.update(ct), d.final()]);
}

export interface SubjectKey {
  keyId: string;
  /** HMAC salt for subject/session pseudonyms. Generated by the database. */
  salt: Buffer;
  /** Unwrapped data-encryption key. Never leaves the process. */
  dek: Buffer;
}

/**
 * WHY THIS IS A FACTORY AND NOT AN OBJECT LITERAL.
 *
 * A SubjectKey rides on PipelineContext, and PipelineContext is passed to code
 * that serialises what it is given. sideEffectDispatcher.enqueueJob puts its
 * payload through JSON.stringify and INSERTs the result into
 * `side_effect_job.payload` — so one careless `enqueueJob('X', { ctx })` would
 * write an unwrapped DEK into a database column, in the clear, next to the
 * ciphertext it decrypts. That is not a hypothetical shape: it is the shape of
 * the code as written.
 *
 * So the key redacts itself on both paths that could carry it out of the
 * process — JSON.stringify (toJSON) and console/util.inspect. Neither is a
 * substitute for not passing it around; both are cheap, and the failure they
 * prevent is unrecoverable and silent.
 */
function makeSubjectKey(keyId: string, salt: Buffer, dek: Buffer): SubjectKey {
  const redacted = { keyId, salt: '[redacted]', dek: '[redacted]' };
  return Object.defineProperties({ keyId, salt, dek } as SubjectKey, {
    toJSON: { value: () => redacted, enumerable: false },
    [inspect.custom]: { value: () => redacted, enumerable: false },
  });
}

interface MaterialRow {
  key_id: string;
  salt: Buffer;
  wrapped_dek: Buffer;
}

/**
 * The one method of pg's Pool/PoolClient this module uses.
 *
 * It is a parameter rather than always `db()` because of R10e. The seed
 * (`scripts/seed-real.ts`) mints keys with this code — deliberately, so the
 * fixture is built by the mechanism under test — but it also writes to
 * `principal`, `safety` and `evidence`, and `hp_app` holds INSERT on none of
 * them (verified: `has_table_privilege('hp_app', ...)` is false for every one).
 * That is correct and must stay correct, so the seed runs on an owner
 * connection of its own and hands it in here.
 *
 * The default keeps every request-path caller on `db()` unchanged.
 */
export type Queryable = Pick<PoolClient, 'query'>;

async function readMaterial(userId: string, exec: Queryable): Promise<SubjectKey | null> {
  const { rows } = await exec.query<MaterialRow>(
    'SELECT key_id, salt, wrapped_dek FROM principal.subject_key_material($1)',
    [userId],
  );
  const row = rows[0];
  if (!row) return null;
  return makeSubjectKey(row.key_id, row.salt, unwrap(row.wrapped_dek));
}

/**
 * Resolved once per request, at the top of the pipeline, and carried on
 * PipelineContext — so every pseudonym in one turn derives from the same salt
 * and nothing downstream needs a round trip.
 *
 * Read first, mint second: in the steady state this is one query. The mint path
 * runs for a subject's first turn, and the re-read after it is not belt and
 * braces — `ensure_subject_key` is idempotent under a race, so if a concurrent
 * request won, OUR dek is not the stored one and using it would encrypt content
 * under a key the row does not name.
 */
export async function getOrMintSubjectKey(userId: string, exec: Queryable = db()): Promise<SubjectKey> {
  const existing = await readMaterial(userId, exec);
  if (existing) return existing;

  const dek = randomBytes(DEK_BYTES);
  const { rows } = await exec.query<{ key_id: string; salt: Buffer; created: boolean }>(
    'SELECT key_id, salt, created FROM principal.ensure_subject_key($1, $2)',
    [userId, wrap(dek)],
  );
  const minted = rows[0];
  if (!minted) throw new Error(`subjectKey: ensure_subject_key returned nothing for ${userId}`);
  if (minted.created) return makeSubjectKey(minted.key_id, minted.salt, dek);

  const raced = await readMaterial(userId, exec);
  if (!raced) {
    // ensure_subject_key said a key exists and the read says it does not. The
    // only way both are true is a destroyed key, and that is not a state to
    // paper over: a subject whose key was destroyed must not get a new one.
    throw new Error(
      `subjectKey: ${userId} has a key that cannot be read — it is destroyed. ` +
        'An erased subject who returns is a new subject (HP-ESC 2.3.4g).',
    );
  }
  return raced;
}

/** AES-256-GCM under the subject's DEK. nonce | tag | ciphertext. */
export function encryptForSubject(key: SubjectKey, plaintext: string): Buffer {
  const nonce = randomBytes(NONCE_BYTES);
  const c = createCipheriv(WRAP_ALG, key.dek, nonce);
  const ct = Buffer.concat([c.update(plaintext, 'utf8'), c.final()]);
  return Buffer.concat([nonce, c.getAuthTag(), ct]);
}

export function decryptForSubject(key: SubjectKey, blob: Buffer): string {
  const nonce = blob.subarray(0, NONCE_BYTES);
  const tag = blob.subarray(NONCE_BYTES, NONCE_BYTES + TAG_BYTES);
  const ct = blob.subarray(NONCE_BYTES + TAG_BYTES);
  const d = createDecipheriv(WRAP_ALG, key.dek, nonce);
  d.setAuthTag(tag);
  return Buffer.concat([d.update(ct), d.final()]).toString('utf8');
}

/**
 * principal.patient_attribute stores its envelope in FOUR columns, not one:
 * payload_ciphertext, cipher_alg, cipher_nonce, key_id. So the concatenated
 * layout above does not apply and these two functions define the split one.
 *
 * THIS CODE IS THE FIRST WRITER AND THE FIRST READER of that table — nothing in
 * the system has ever created a patient_attribute row — so the convention is
 * set here rather than discovered, and written down because a wrong guess is
 * indistinguishable from corrupt data:
 *
 *   cipher_alg          the literal 'AES-256-GCM'
 *   cipher_nonce        the 12-byte GCM nonce, alone
 *   payload_ciphertext  ciphertext || 16-byte GCM tag
 *   plaintext           UTF-8 JSON
 *
 * The tag rides with the ciphertext rather than in a fifth column because the
 * schema has no column for it, and appending is the convention every GCM
 * library defaults to.
 */
export const ATTRIBUTE_CIPHER_ALG = 'AES-256-GCM';

export function encryptAttribute(key: SubjectKey, payload: unknown): {
  ciphertext: Buffer;
  nonce: Buffer;
  alg: string;
} {
  const nonce = randomBytes(NONCE_BYTES);
  const c = createCipheriv(WRAP_ALG, key.dek, nonce);
  const body = Buffer.concat([c.update(JSON.stringify(payload), 'utf8'), c.final()]);
  return { ciphertext: Buffer.concat([body, c.getAuthTag()]), nonce, alg: ATTRIBUTE_CIPHER_ALG };
}

export function decryptAttribute(
  key: SubjectKey,
  ciphertext: Buffer,
  nonce: Buffer,
  alg: string,
): unknown {
  // Checked rather than assumed: the column is free text, and a row written
  // under a different algorithm would otherwise be fed to AES-GCM and fail with
  // an authentication error that says nothing about the real cause.
  if (alg !== ATTRIBUTE_CIPHER_ALG) {
    throw new Error(
      `subjectKey: attribute cipher_alg is "${alg}", expected "${ATTRIBUTE_CIPHER_ALG}". ` +
        'Rows written under another algorithm need their own reader; guessing would ' +
        'surface as an authentication failure and be mistaken for corruption.',
    );
  }
  if (ciphertext.length < TAG_BYTES) {
    throw new Error(`subjectKey: attribute ciphertext is ${ciphertext.length} bytes, too short to carry a GCM tag`);
  }
  const body = ciphertext.subarray(0, ciphertext.length - TAG_BYTES);
  const tag = ciphertext.subarray(ciphertext.length - TAG_BYTES);
  const d = createDecipheriv(WRAP_ALG, key.dek, nonce);
  d.setAuthTag(tag);
  return JSON.parse(Buffer.concat([d.update(body), d.final()]).toString('utf8'));
}
