-- HealthPlus migration: 19. Migration 020 — seeding the attribute registry
-- Source: HP-SCHEMA-001 Annex A Extension
-- Extracted verbatim from the design doc's SQL fences; not yet run against a live database.

-- ============================================================================
-- MIGRATION 020 — seed: 101 entity types, 153 attribute contracts
-- ============================================================================
INSERT INTO evidence.domain_entity_type
  (entity_type, schema_name, table_name, rls_scope, blueprint_ref, adopted_version)
SELECT v.entity_type, v.schema_name, v.table_name, v.rls_scope, v.blueprint_ref,
       'HP-SCHEMA-001 v0.2'
FROM (VALUES
  ('accommodation_option', 'domain', 'accommodation_option', 'PROVIDER', '§40 medical_tourism_*'),
  ('accreditation_body', 'domain', 'accreditation_body', 'GLOBAL', '§40 HOSPITAL'),
  ('activity', 'domain', 'activity', 'GLOBAL', '§40 physical_activity_*'),
  ('activity_intensity_band', 'domain', 'activity_intensity_band', 'GLOBAL', '§40 physical_activity_*'),
  ('activity_precaution', 'domain', 'activity_precaution', 'GLOBAL', '§40 physical_activity_*'),
  ('activity_progression_stage', 'domain', 'activity_progression_stage', 'GLOBAL', '§40 physical_activity_*'),
  ('activity_recommendation', 'domain', 'activity_recommendation', 'GLOBAL', '§40 physical_activity_*'),
  ('aftercare_template', 'domain', 'aftercare_template', 'GLOBAL', '§40 medical_tourism_*'),
  ('care_pathway_stage', 'domain', 'care_pathway_stage', 'GLOBAL', '§40 medical_tourism_*'),
  ('cause', 'domain', 'cause', 'GLOBAL', '§40 DISEASE'),
  ('cessation_support', 'domain', 'cessation_support', 'GLOBAL', '§40 lifestyle_*'),
  ('clinical_indicator', 'domain', 'clinical_indicator', 'GLOBAL', '§40 DISEASE'),
  ('complication', 'domain', 'complication', 'GLOBAL', '§40 DISEASE'),
  ('country', 'domain', 'country', 'GLOBAL', '§40 COUNTRY'),
  ('country_guideline', 'domain', 'country_guideline', 'GLOBAL', '§40 COUNTRY'),
  ('destination_profile', 'domain', 'destination_profile', 'GLOBAL', '§40 medical_tourism_*'),
  ('diagnostic_test', 'domain', 'diagnostic_test', 'GLOBAL', '§40 DISEASE'),
  ('disease', 'domain', 'disease', 'GLOBAL', '§40 DISEASE'),
  ('disease_activity', 'domain', 'disease_activity', 'GLOBAL', '§40 DISEASE'),
  ('disease_category', 'domain', 'disease_category', 'GLOBAL', '§40 DISEASE'),
  ('disease_cause', 'domain', 'disease_cause', 'GLOBAL', '§40 DISEASE'),
  ('disease_complication', 'domain', 'disease_complication', 'GLOBAL', '§40 DISEASE'),
  ('disease_diagnostic_test', 'domain', 'disease_diagnostic_test', 'GLOBAL', '§40 DISEASE'),
  ('disease_icd_code', 'domain', 'disease_icd_code', 'GLOBAL', '§40 DISEASE'),
  ('disease_lifestyle', 'domain', 'disease_lifestyle', 'GLOBAL', '§40 DISEASE'),
  ('disease_nutrition', 'domain', 'disease_nutrition', 'GLOBAL', '§40 DISEASE'),
  ('disease_occupational_exposure', 'domain', 'disease_occupational_exposure', 'GLOBAL', '§40 DISEASE'),
  ('disease_risk_factor', 'domain', 'disease_risk_factor', 'GLOBAL', '§40 DISEASE'),
  ('disease_severity_level', 'domain', 'disease_severity_level', 'GLOBAL', '§7'),
  ('disease_severity_model', 'domain', 'disease_severity_model', 'GLOBAL', '§7 / §40 DISEASE'),
  ('disease_specialty', 'domain', 'disease_specialty', 'GLOBAL', '§40 DISEASE'),
  ('disease_symptom', 'domain', 'disease_symptom', 'GLOBAL', '§40 DISEASE'),
  ('disease_treatment', 'domain', 'disease_treatment', 'GLOBAL', '§40 DISEASE'),
  ('environment', 'domain', 'environment', 'GLOBAL', '§40 COUNTRY'),
  ('follow_up_milestone', 'domain', 'follow_up_milestone', 'GLOBAL', '§40 FOLLOW_UP'),
  ('follow_up_schedule', 'domain', 'follow_up_schedule', 'GLOBAL', '§40 FOLLOW_UP'),
  ('food_drug_interaction', 'domain', 'food_drug_interaction', 'GLOBAL', '§40 nutrition_*'),
  ('food_item', 'domain', 'food_item', 'GLOBAL', '§40 nutrition_*'),
  ('food_nutrient', 'domain', 'food_nutrient', 'GLOBAL', '§40 nutrition_*'),
  ('food_restriction_link', 'domain', 'food_restriction_link', 'GLOBAL', '§40 nutrition_*'),
  ('functional_capacity_measure', 'domain', 'functional_capacity_measure', 'GLOBAL', '§40 physical_activity_*'),
  ('guideline', 'domain', 'guideline', 'GLOBAL', '§40 GUIDELINES'),
  ('guideline_recommendation', 'domain', 'guideline_recommendation', 'GLOBAL', '§40 GUIDELINES'),
  ('hospital', 'domain', 'hospital', 'PROVIDER', '§40 HOSPITAL'),
  ('hospital_accreditation', 'domain', 'hospital_accreditation', 'PROVIDER', '§40 HOSPITAL'),
  ('hospital_cost', 'domain', 'hospital_cost', 'PROVIDER', '§40 HOSPITAL -> COSTS'),
  ('hospital_specialist', 'domain', 'hospital_specialist', 'PROVIDER', '§40 HOSPITAL'),
  ('hospital_treatment', 'domain', 'hospital_treatment', 'PROVIDER', '§40 HOSPITAL'),
  ('hospital_treatment_outcome', 'domain', 'hospital_treatment_outcome', 'PROVIDER', '§40 HOSPITAL'),
  ('icd_code', 'domain', 'icd_code', 'GLOBAL', '§40 DISEASE'),
  ('interpreter_service', 'domain', 'interpreter_service', 'PROVIDER', '§40 medical_tourism_*'),
  ('lifestyle_domain_ref', 'domain', 'lifestyle_domain_ref', 'GLOBAL', '§40 lifestyle_*'),
  ('lifestyle_recommendation', 'domain', 'lifestyle_recommendation', 'GLOBAL', '§40 lifestyle_*'),
  ('lifestyle_risk_behaviour', 'domain', 'lifestyle_risk_behaviour', 'GLOBAL', '§40 lifestyle_*'),
  ('lifestyle_screening_item', 'domain', 'lifestyle_screening_item', 'GLOBAL', '§40 lifestyle_*'),
  ('lifestyle_screening_tool', 'domain', 'lifestyle_screening_tool', 'GLOBAL', '§40 lifestyle_*'),
  ('medical_tourism_package', 'domain', 'medical_tourism_package', 'PROVIDER', '§40 medical_tourism_*'),
  ('medical_visa', 'domain', 'medical_visa', 'GLOBAL', '§40 COUNTRY'),
  ('medication', 'domain', 'medication', 'GLOBAL', '§40 TREATMENTS'),
  ('monitoring_parameter', 'domain', 'monitoring_parameter', 'GLOBAL', '§40 MONITORING'),
  ('monitoring_protocol', 'domain', 'monitoring_protocol', 'GLOBAL', '§40 MONITORING'),
  ('nutrient', 'domain', 'nutrient', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_pattern', 'domain', 'nutrition_pattern', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_pattern_component', 'domain', 'nutrition_pattern_component', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_recommendation', 'domain', 'nutrition_recommendation', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_restriction', 'domain', 'nutrition_restriction', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_screening_item', 'domain', 'nutrition_screening_item', 'GLOBAL', '§40 nutrition_*'),
  ('nutrition_screening_tool', 'domain', 'nutrition_screening_tool', 'GLOBAL', '§40 nutrition_*'),
  ('occupational_exposure', 'domain', 'occupational_exposure', 'GLOBAL', '§40 lifestyle_*'),
  ('package_component', 'domain', 'package_component', 'PROVIDER', '§40 medical_tourism_*'),
  ('package_pathway_stage', 'domain', 'package_pathway_stage', 'PROVIDER', '§40 medical_tourism_*'),
  ('procedure', 'domain', 'procedure', 'GLOBAL', '§40 TREATMENTS'),
  ('provider_submission', 'domain', 'provider_submission', 'PROVIDER', '§40 (derived)'),
  ('reference_value', 'domain', 'reference_value', 'GLOBAL', '§40 REFERENCE_VALUES'),
  ('regulation', 'domain', 'regulation', 'GLOBAL', '§40 REGULATIONS'),
  ('regulation_provision', 'domain', 'regulation_provision', 'GLOBAL', '§40 REGULATIONS'),
  ('rehabilitation', 'domain', 'rehabilitation', 'GLOBAL', '§40 TREATMENTS'),
  ('repatriation_requirement', 'domain', 'repatriation_requirement', 'GLOBAL', '§40 medical_tourism_*'),
  ('risk_factor', 'domain', 'risk_factor', 'GLOBAL', '§40 DISEASE'),
  ('sentiment_subject', 'domain', 'sentiment_subject', 'GLOBAL', '§39 / §1.5.5'),
  ('specialist', 'domain', 'specialist', 'PROVIDER', '§40 HOSPITAL'),
  ('specialty', 'domain', 'specialty', 'GLOBAL', '§40 DISEASE'),
  ('surgery', 'domain', 'surgery', 'GLOBAL', '§40 TREATMENTS'),
  ('symptom', 'domain', 'symptom', 'GLOBAL', '§40 DISEASE'),
  ('transfer_service', 'domain', 'transfer_service', 'PROVIDER', '§40 medical_tourism_*'),
  ('travel_fitness_criterion', 'domain', 'travel_fitness_criterion', 'GLOBAL', '§40 medical_tourism_* / §25'),
  ('travel_requirement', 'domain', 'travel_requirement', 'GLOBAL', '§40 medical_tourism_* / §25'),
  ('treatment', 'domain', 'treatment', 'GLOBAL', '§40 TREATMENTS'),
  ('treatment_activity', 'domain', 'treatment_activity', 'GLOBAL', '§40 TREATMENTS'),
  ('treatment_contraindication', 'domain', 'treatment_contraindication', 'GLOBAL', '§40 TREATMENTS'),
  ('treatment_eligibility_criterion', 'domain', 'treatment_eligibility_criterion', 'GLOBAL', '§40 TREATMENTS'),
  ('treatment_outcome', 'domain', 'treatment_outcome', 'GLOBAL', '§40 TREATMENTS -> OUTCOMES'),
  ('wellness_category', 'domain', 'wellness_category', 'GLOBAL', '§40 wellness_*'),
  ('wellness_component', 'domain', 'wellness_component', 'PROVIDER', '§40 wellness_*'),
  ('wellness_contraindication', 'domain', 'wellness_contraindication', 'GLOBAL', '§40 wellness_*'),
  ('wellness_modality', 'domain', 'wellness_modality', 'GLOBAL', '§40 wellness_*'),
  ('wellness_outcome_measure', 'domain', 'wellness_outcome_measure', 'PROVIDER', '§40 wellness_*'),
  ('wellness_practitioner', 'domain', 'wellness_practitioner', 'PROVIDER', '§40 wellness_*'),
  ('wellness_practitioner_credential', 'domain', 'wellness_practitioner_credential', 'PROVIDER', '§40 wellness_*'),
  ('wellness_program', 'domain', 'wellness_program', 'PROVIDER', '§40 wellness_*'),
  ('wellness_program_modality', 'domain', 'wellness_program_modality', 'PROVIDER', '§40 wellness_*')
) AS v(entity_type, schema_name, table_name, rls_scope, blueprint_ref);

INSERT INTO evidence.domain_attribute_kind
  (entity_type, attribute, expected_claim_kind, min_claims, max_claims, requires_marker,
   charter_clause, blueprint_ref, adopted_version, adopted_by, effective_from)
SELECT v.entity_type, v.attribute, v.expected_claim_kind::claim_kind,
       v.min_claims::smallint, v.max_claims::smallint, v.requires_marker,
       v.charter_clause, v.blueprint_ref, 'HP-SCHEMA-001 v0.2',
       '00000000-0000-0000-0000-0000000000aa'::uuid, now()
FROM (VALUES
  ('accommodation_option', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('accommodation_option', 'price', 'COST', 0, NULL, true, 'HP-ESC 3.3.3', '§40 medical_tourism_*'),
  ('accreditation_body', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 HOSPITAL'),
  ('accreditation_body', 'standard', 'GUIDELINE', 0, NULL, false, 'HP-ESC 1.2.6', '§40 HOSPITAL'),
  ('activity', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 physical_activity_*'),
  ('activity_intensity_band', 'definition', 'REFERENCE_RANGE', 1, NULL, false, 'HP-ESC 3.5.2', '§40 physical_activity_*'),
  ('activity_precaution', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.2.6', '§40 physical_activity_*'),
  ('activity_progression_stage', 'timing', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 physical_activity_*'),
  ('activity_recommendation', 'recommendation_text', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 physical_activity_*'),
  ('activity_recommendation', 'volume_target', 'GUIDELINE', 0, NULL, false, 'HP-ESC 3.5.6', '§40 physical_activity_*'),
  ('aftercare_template', 'content', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1 / 4.5.1a', '§40 medical_tourism_*'),
  ('cause', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('cessation_support', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 lifestyle_*'),
  ('cessation_support', 'effectiveness', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7', '§40 lifestyle_*'),
  ('clinical_indicator', 'what_it_measures', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 3.1.7', '§40 DISEASE'),
  ('clinical_indicator', 'unit_rationale', 'GENERAL_EDUCATION', 0, 1, false, 'HP-ESC 3.5.3', '§40 DISEASE'),
  ('complication', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('country', 'healthcare_system', 'GENERAL_EDUCATION', 0, NULL, false, 'HP-ESC 2.1.1', '§40 COUNTRY'),
  ('country', 'context', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.5.4', '§40 COUNTRY'),
  ('country_guideline', 'adoption_status', 'LEGAL_REGULATORY', 1, NULL, false, 'HP-ESC 3.7.1', '§40 COUNTRY'),
  ('destination_profile', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('destination_profile', 'specialty_availability', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('diagnostic_test', 'what_it_measures', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 3.1.7', '§40 DISEASE'),
  ('diagnostic_test', 'why_ordered', 'GENERAL_EDUCATION', 0, NULL, false, 'HP-ESC 3.1.7', '§40 DISEASE'),
  ('diagnostic_test', 'preparation', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.5.4', '§40 DISEASE'),
  ('disease', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('disease', 'prevalence', 'EPIDEMIOLOGY', 0, NULL, false, 'HP-ESC 1.7.1', '§40 DISEASE'),
  ('disease', 'prognosis', 'CLINICAL_EFFICACY', 0, NULL, false, 'HP-ESC 1.3.7', '§40 DISEASE'),
  ('disease', 'natural_history', 'GENERAL_EDUCATION', 0, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('disease_activity', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 DISEASE'),
  ('disease_category', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('disease_cause', 'association', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 DISEASE'),
  ('disease_complication', 'association', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 DISEASE'),
  ('disease_complication', 'incidence', 'EPIDEMIOLOGY', 0, NULL, false, 'HP-ESC 1.9.7', '§40 DISEASE'),
  ('disease_diagnostic_test', 'indication', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 DISEASE'),
  ('disease_lifestyle', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 DISEASE'),
  ('disease_nutrition', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 DISEASE'),
  ('disease_occupational_exposure', 'association', 'EPIDEMIOLOGY', 1, NULL, false, 'HP-ESC 1.9.7', '§40 DISEASE'),
  ('disease_risk_factor', 'association', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 DISEASE'),
  ('disease_risk_factor', 'effect_size', 'CLINICAL_EFFICACY', 0, NULL, false, 'HP-ESC 1.3.7', '§40 DISEASE'),
  ('disease_severity_level', 'criteria', 'GUIDELINE', 1, NULL, false, 'HP-ESC 4.7.2', '§7'),
  ('disease_severity_level', 'score_definition', 'GUIDELINE', 0, NULL, false, 'HP-ESC 4.7.2', '§7'),
  ('disease_severity_level', 'recommended_escalation', 'GUIDELINE', 0, NULL, false, 'HP-ESC 4.7.2', '§7'),
  ('disease_severity_model', 'criteria', 'GUIDELINE', 1, NULL, false, 'HP-ESC 4.7.2', '§7 / §40 DISEASE'),
  ('disease_severity_model', 'source_guideline', 'GUIDELINE', 1, NULL, false, 'HP-ESC 4.7.2', '§7 / §40 DISEASE'),
  ('disease_severity_model', 'limitations', 'GUIDELINE', 0, NULL, false, 'HP-ESC 4.7.2', '§7 / §40 DISEASE'),
  ('disease_symptom', 'association', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 DISEASE'),
  ('disease_symptom', 'frequency', 'EPIDEMIOLOGY', 0, NULL, false, 'HP-ESC 1.9.7', '§40 DISEASE'),
  ('disease_treatment', 'indication', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 DISEASE'),
  ('disease_treatment', 'line_of_therapy_basis', 'GUIDELINE', 0, NULL, false, 'HP-ESC 3.6.2', '§40 DISEASE'),
  ('environment', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 COUNTRY'),
  ('environment', 'vaccination_requirement', 'LEGAL_REGULATORY', 0, NULL, false, 'HP-ESC 3.7.1', '§40 COUNTRY'),
  ('follow_up_milestone', 'timing', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1 / AMB-S-08', '§40 FOLLOW_UP'),
  ('follow_up_schedule', 'description', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 FOLLOW_UP'),
  ('food_drug_interaction', 'mechanism', 'MEDICATION', 1, NULL, false, 'HP-ESC 3.12.2', '§40 nutrition_*'),
  ('food_drug_interaction', 'management', 'GUIDELINE', 0, NULL, false, 'HP-ESC 3.6.1', '§40 nutrition_*'),
  ('food_item', 'description', 'GENERAL_EDUCATION', 0, NULL, false, 'HP-ESC 2.1.1', '§40 nutrition_*'),
  ('food_nutrient', 'composition', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 nutrition_*'),
  ('food_restriction_link', 'basis', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 1.0.1', '§40 nutrition_*'),
  ('functional_capacity_measure', 'what_it_measures', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 3.1.7', '§40 physical_activity_*'),
  ('functional_capacity_measure', 'threshold', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.1', '§40 physical_activity_*'),
  ('guideline', 'scope', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 GUIDELINES'),
  ('guideline', 'methodology', 'GUIDELINE', 0, 1, false, 'HP-ESC 1.2.3', '§40 GUIDELINES'),
  ('guideline_recommendation', 'recommendation_text', 'GUIDELINE', 1, 1, false, 'HP-ESC 3.9.4', '§40 GUIDELINES'),
  ('hospital', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.4.3', '§40 HOSPITAL'),
  ('hospital', 'languages_spoken', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.4.3', '§40 HOSPITAL'),
  ('hospital', 'bed_count', 'LOGISTICS', 0, 1, false, 'HP-ESC 1.4.3', '§40 HOSPITAL'),
  ('hospital', 'contact', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.4.3', '§40 HOSPITAL'),
  ('hospital_accreditation', 'status', 'ACCREDITATION', 1, NULL, false, 'HP-ESC 1.2.6 / 3.4.3', '§40 HOSPITAL'),
  ('hospital_cost', 'amount', 'COST', 1, NULL, true, 'HP-ESC 3.3.1 / 3.3.3', '§40 HOSPITAL -> COSTS'),
  ('hospital_cost', 'inclusions', 'COST', 0, NULL, true, 'HP-ESC 3.3.4', '§40 HOSPITAL -> COSTS'),
  ('hospital_cost', 'exclusions', 'COST', 0, NULL, true, 'HP-ESC 3.3.4', '§40 HOSPITAL -> COSTS'),
  ('hospital_specialist', 'affiliation', 'PROVIDER_CREDENTIAL', 1, NULL, true, 'HP-ESC 1.7.1', '§40 HOSPITAL'),
  ('hospital_treatment', 'availability', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.4.3', '§40 HOSPITAL'),
  ('hospital_treatment_outcome', 'rate', 'PROVIDER_OUTCOME', 1, NULL, true, 'HP-ESC 1.4.4 / 3.4.1', '§40 HOSPITAL'),
  ('icd_code', 'title_source', 'GENERAL_EDUCATION', 0, 1, false, 'HP-ESC 1.9.1', '§40 DISEASE'),
  ('interpreter_service', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('lifestyle_domain_ref', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 lifestyle_*'),
  ('lifestyle_recommendation', 'recommendation_text', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 lifestyle_*'),
  ('lifestyle_risk_behaviour', 'definition', 'REFERENCE_RANGE', 1, NULL, false, 'HP-ESC 3.5.6', '§40 lifestyle_*'),
  ('lifestyle_risk_behaviour', 'health_effect', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7', '§40 lifestyle_*'),
  ('lifestyle_screening_item', 'item_text', 'GUIDELINE', 1, 1, false, 'HP-ESC 3.9.4', '§40 lifestyle_*'),
  ('lifestyle_screening_tool', 'instrument_text', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.9.4', '§40 lifestyle_*'),
  ('lifestyle_screening_tool', 'cutoffs', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.6', '§40 lifestyle_*'),
  ('medical_tourism_package', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('medical_tourism_package', 'price', 'COST', 0, NULL, true, 'HP-ESC 3.3.3', '§40 medical_tourism_*'),
  ('medical_tourism_package', 'duration', 'LOGISTICS', 0, 1, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('medical_visa', 'requirements', 'LEGAL_REGULATORY', 1, NULL, false, 'HP-ESC 3.7.1', '§40 COUNTRY'),
  ('medical_visa', 'processing_time', 'LOGISTICS', 0, NULL, false, 'HP-ESC 1.5.4', '§40 COUNTRY'),
  ('medical_visa', 'fee', 'COST', 0, NULL, false, 'HP-ESC 3.3.1', '§40 COUNTRY'),
  ('medication', 'dosing_guidance', 'MEDICATION', 0, NULL, false, 'HP-ESC 3.12.2', '§40 TREATMENTS'),
  ('medication', 'approval_status', 'LEGAL_REGULATORY', 0, NULL, false, 'HP-ESC 3.7.1', '§40 TREATMENTS'),
  ('medication', 'interaction_profile', 'MEDICATION', 0, NULL, false, 'HP-ESC 1.5.3', '§40 TREATMENTS'),
  ('monitoring_parameter', 'interval', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.5.6', '§40 MONITORING'),
  ('monitoring_protocol', 'description', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 MONITORING'),
  ('nutrient', 'function', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 nutrition_*'),
  ('nutrient', 'reference_intake', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.1', '§40 nutrition_*'),
  ('nutrition_pattern', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 nutrition_*'),
  ('nutrition_pattern', 'evidence', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7', '§40 nutrition_*'),
  ('nutrition_pattern_component', 'guidance', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 nutrition_*'),
  ('nutrition_recommendation', 'recommendation_text', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 nutrition_*'),
  ('nutrition_recommendation', 'target_amount', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.6', '§40 nutrition_*'),
  ('nutrition_restriction', 'definition', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 nutrition_*'),
  ('nutrition_screening_item', 'item_text', 'GUIDELINE', 1, 1, false, 'HP-ESC 3.9.4', '§40 nutrition_*'),
  ('nutrition_screening_tool', 'instrument_text', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.9.4', '§40 nutrition_*'),
  ('nutrition_screening_tool', 'cutoffs', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.6', '§40 nutrition_*'),
  ('occupational_exposure', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 lifestyle_*'),
  ('occupational_exposure', 'classification', 'LEGAL_REGULATORY', 0, NULL, false, 'HP-ESC 3.7.1', '§40 lifestyle_*'),
  ('package_component', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('package_component', 'price', 'COST', 0, NULL, true, 'HP-ESC 3.3.3', '§40 medical_tourism_*'),
  ('procedure', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 TREATMENTS'),
  ('procedure', 'typical_duration', 'LOGISTICS', 0, 1, false, 'HP-ESC 1.5.4', '§40 TREATMENTS'),
  ('reference_value', 'range', 'REFERENCE_RANGE', 1, NULL, false, 'HP-ESC 3.5.1', '§40 REFERENCE_VALUES'),
  ('reference_value', 'unit_conversion', 'REFERENCE_RANGE', 0, NULL, false, 'HP-ESC 3.5.3', '§40 REFERENCE_VALUES'),
  ('regulation', 'provision_summary', 'LEGAL_REGULATORY', 1, NULL, false, 'HP-ESC 3.7.1', '§40 REGULATIONS'),
  ('regulation_provision', 'provision_text', 'LEGAL_REGULATORY', 1, 1, false, 'HP-ESC 3.9.4', '§40 REGULATIONS'),
  ('rehabilitation', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 TREATMENTS'),
  ('rehabilitation', 'protocol', 'GUIDELINE', 0, NULL, false, 'HP-ESC 3.6.1', '§40 TREATMENTS'),
  ('repatriation_requirement', 'requirement_text', 'LEGAL_REGULATORY', 1, NULL, false, 'HP-ESC 3.7.1', '§40 medical_tourism_*'),
  ('risk_factor', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('sentiment_subject', 'sentiment', 'SENTIMENT', 0, NULL, false, 'HP-ESC 1.5.5', '§39 / §1.5.5'),
  ('specialist', 'qualification', 'PROVIDER_CREDENTIAL', 0, NULL, true, 'HP-ESC 3.4.4', '§40 HOSPITAL'),
  ('specialist', 'registration', 'PROVIDER_CREDENTIAL', 0, NULL, false, 'HP-ESC 1.2.6', '§40 HOSPITAL'),
  ('specialist', 'years_experience', 'PROVIDER_CREDENTIAL', 0, 1, true, 'HP-ESC 3.4.4', '§40 HOSPITAL'),
  ('specialist', 'procedure_volume', 'PROVIDER_OUTCOME', 0, NULL, true, 'HP-ESC 1.4.4', '§40 HOSPITAL'),
  ('specialty', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('surgery', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 TREATMENTS'),
  ('surgery', 'typical_length_of_stay', 'CLINICAL_EFFICACY', 0, NULL, false, 'HP-ESC 1.9.7', '§40 TREATMENTS'),
  ('surgery', 'anaesthesia_guidance', 'GUIDELINE', 0, NULL, false, 'HP-ESC 3.2.3', '§40 TREATMENTS'),
  ('symptom', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 DISEASE'),
  ('transfer_service', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 medical_tourism_*'),
  ('transfer_service', 'price', 'COST', 0, NULL, true, 'HP-ESC 3.3.3', '§40 medical_tourism_*'),
  ('travel_fitness_criterion', 'criterion_text', 'GUIDELINE', 1, 1, false, 'HP-ESC 3.2.3 / C-25', '§40 medical_tourism_* / §25'),
  ('travel_requirement', 'requirement_text', 'LEGAL_REGULATORY', 1, NULL, false, 'HP-ESC 3.7.1', '§40 medical_tourism_* / §25'),
  ('treatment', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 TREATMENTS'),
  ('treatment', 'mechanism', 'GENERAL_EDUCATION', 0, NULL, false, 'HP-ESC 2.1.1', '§40 TREATMENTS'),
  ('treatment', 'efficacy', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7', '§40 TREATMENTS'),
  ('treatment', 'typical_recovery', 'CLINICAL_EFFICACY', 0, NULL, false, 'HP-ESC 1.9.7', '§40 TREATMENTS'),
  ('treatment_activity', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.6.1', '§40 TREATMENTS'),
  ('treatment_contraindication', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.2.6', '§40 TREATMENTS'),
  ('treatment_eligibility_criterion', 'criterion_text', 'ELIGIBILITY', 1, 1, false, 'HP-ESC 3.2.6', '§40 TREATMENTS'),
  ('treatment_outcome', 'rate', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7 / 1.9.7', '§40 TREATMENTS -> OUTCOMES'),
  ('wellness_category', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 wellness_*'),
  ('wellness_component', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 wellness_*'),
  ('wellness_contraindication', 'basis', 'GUIDELINE', 1, NULL, false, 'HP-ESC 3.2.6', '§40 wellness_*'),
  ('wellness_modality', 'description', 'GENERAL_EDUCATION', 1, NULL, false, 'HP-ESC 2.1.1', '§40 wellness_*'),
  ('wellness_modality', 'evidence', 'CLINICAL_EFFICACY', 2, NULL, false, 'HP-ESC 1.3.7 / 1.0.7', '§40 wellness_*'),
  ('wellness_modality', 'regulatory_status', 'LEGAL_REGULATORY', 0, NULL, false, 'HP-ESC 3.7.1', '§40 wellness_*'),
  ('wellness_outcome_measure', 'rate', 'PROVIDER_OUTCOME', 0, NULL, true, 'HP-ESC 1.4.4', '§40 wellness_*'),
  ('wellness_practitioner_credential', 'credential', 'PROVIDER_CREDENTIAL', 1, NULL, true, 'HP-ESC 3.4.4', '§40 wellness_*'),
  ('wellness_program', 'description', 'LOGISTICS', 1, NULL, false, 'HP-ESC 1.5.4', '§40 wellness_*'),
  ('wellness_program', 'price', 'COST', 0, NULL, true, 'HP-ESC 3.3.3', '§40 wellness_*'),
  ('wellness_program', 'claimed_benefit', 'CLINICAL_EFFICACY', 2, NULL, true, 'HP-ESC 1.4.4 / 1.0.7', '§40 wellness_*')
) AS v(entity_type, attribute, expected_claim_kind, min_claims, max_claims,
       requires_marker, charter_clause, blueprint_ref);
