-- HealthPlus migration: 21. Migration 022 — the 225-row `claim_policy` matrix
-- Source: HP-SCHEMA-001 Annex A Extension
-- Extracted verbatim from the design doc's SQL fences; not yet run against a live database.

-- ============================================================================
-- MIGRATION 022 — attribution markers, category state, the 225-row gate
-- ============================================================================

-- §1.4.4 / §3.3.9 / §3.4.3 / §1.3.4: the mandatory strings, as data. The composer
-- renders these verbatim; it does not compose them, and §3.9.5 forbids the model
-- altering any of them.
CREATE TABLE safety.attribution_marker (
  id             text PRIMARY KEY,
  body           text NOT NULL,
  charter_clause text NOT NULL,
  verbatim_required boolean NOT NULL DEFAULT true,
  approved_by    uuid REFERENCES principal.clinician(user_id),
  approved_at    timestamptz,
  adopted_version text NOT NULL
);

INSERT INTO safety.attribution_marker (id, body, charter_clause, adopted_version) VALUES
  ('HP-M-SELF-REPORT',
   'Reported by the hospital; not independently verified.',
   'HP-ESC 1.4.4', 'HP-SCHEMA-001 v0.3'),
  ('HP-M-CLAIMED-NOT-VERIFIED',
   'Claimed by provider, not verified.',
   'HP-ESC 3.4.3', 'HP-SCHEMA-001 v0.3'),
  ('HP-M-INDICATIVE-COST',
   'Indicative estimate only, based on [source] as of [date]. Not a quotation. '
   'Final cost is set by the provider after assessment and may differ.',
   'HP-ESC 3.3.9', 'HP-SCHEMA-001 v0.3'),
  ('HP-M-OPINION',
   'Patient opinion. Not a clinical quality measure.',
   'HP-ESC 1.5.5', 'HP-SCHEMA-001 v0.3'),
  ('HP-M-PREPRINT',
   'Preprint — not peer reviewed.',
   'HP-ESC 1.3.4', 'HP-SCHEMA-001 v0.3');

ALTER TABLE evidence.claim_policy
  ADD CONSTRAINT fk_claim_policy_marker
    FOREIGN KEY (marker_id) REFERENCES safety.attribution_marker(id),
  -- an attributed disposition without a marker is just a permission
  ADD CONSTRAINT c_attributed_needs_marker CHECK (
    disposition <> 'PERMITTED_ATTRIBUTED' OR marker_id IS NOT NULL),
  -- §1.3.7: corroboration means more than one source, by definition
  ADD CONSTRAINT c_corroboration_needs_two CHECK (
    disposition <> 'REQUIRES_CORROBORATION' OR min_sources >= 2);

-- §2.3.2: the second lock. Enabling a category is its own recorded act.
CREATE TABLE safety.response_category_state (
  category         response_category PRIMARY KEY,
  enabled          boolean NOT NULL,
  enabled_by       uuid REFERENCES principal.clinician(user_id),
  enabled_at       timestamptz,
  board_minute_ref text,
  charter_clause   text NOT NULL,
  adopted_version  text NOT NULL,
  -- §2.3.2: re-enablement requires an explicit, recorded, per-market decision of the
  -- Clinical Governance Board. A boolean flipped in a migration is not that.
  CONSTRAINT c_enablement_attributed CHECK (
    enabled = false OR category <> 'CLINICAL_DECISION'
    OR (enabled_by IS NOT NULL AND enabled_at IS NOT NULL AND board_minute_ref IS NOT NULL))
);

INSERT INTO safety.response_category_state
  (category, enabled, charter_clause, adopted_version) VALUES
  ('INFORMATIONAL',     true,  'HP-ESC 2.5 (v1 availability: On)',  'HP-SCHEMA-001 v0.3'),
  ('DECISION_SUPPORT',  true,  'HP-ESC 2.5 (v1 availability: On)',  'HP-SCHEMA-001 v0.3'),
  ('CLINICAL_DECISION', false, 'HP-ESC 2.3.2 (out of scope for v1)','HP-SCHEMA-001 v0.3');

-- ---- the gate, fail-closed twice ----
CREATE OR REPLACE FUNCTION evidence.policy_for(
  p_tier source_tier, p_kind claim_kind, p_cat response_category
) RETURNS evidence.claim_policy LANGUAGE plpgsql STABLE AS $$
DECLARE r evidence.claim_policy; cat_on boolean;
BEGIN
  -- lock 1: §2.3.2 category enablement, independent of the matrix
  SELECT s.enabled INTO cat_on
    FROM safety.response_category_state s WHERE s.category = p_cat;
  IF NOT COALESCE(cat_on, false) THEN
    r.tier := p_tier; r.kind := p_kind; r.category := p_cat;
    r.disposition := 'PROHIBITED';
    r.min_sources := 1;
    r.charter_clause := 'HP-ESC 2.3.2 category disabled';
    RETURN r;
  END IF;
  -- lock 2: §3.0.3 default-deny — absence of a row is a prohibition, never a permission
  SELECT * INTO r FROM evidence.claim_policy
   WHERE tier = p_tier AND kind = p_kind AND category = p_cat
     AND effective_from <= now()
   ORDER BY effective_from DESC LIMIT 1;
  IF NOT FOUND THEN
    r.tier := p_tier; r.kind := p_kind; r.category := p_cat;
    r.disposition := 'PROHIBITED';
    r.min_sources := 1;
    r.charter_clause := 'HP-ESC 3.0.3 default-deny';
  END IF;
  RETURN r;
END $$;

-- ---- the 225 rows ----
INSERT INTO evidence.claim_policy
  (tier, kind, category, disposition, confidence_cap, min_sources, marker_id,
   charter_clause, adopted_version, adopted_by, effective_from)
SELECT v.tier::source_tier, v.kind::claim_kind, v.category::response_category,
       v.disposition::policy_disposition, v.confidence_cap::numeric(3,2),
       v.min_sources::smallint, v.marker_id, v.charter_clause,
       'HP-SCHEMA-001 v0.3', '00000000-0000-0000-0000-0000000000aa'::uuid,
       TIMESTAMPTZ '2026-08-29 00:00:00+00'
FROM (VALUES
  ('TIER_1', 'GENERAL_EDUCATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.1.3'),
  ('TIER_1', 'GENERAL_EDUCATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.2.2'),
  ('TIER_1', 'GENERAL_EDUCATION', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'GENERAL_EDUCATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.1.3'),
  ('TIER_2', 'GENERAL_EDUCATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.2.2'),
  ('TIER_2', 'GENERAL_EDUCATION', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'GENERAL_EDUCATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.1.3'),
  ('TIER_3', 'GENERAL_EDUCATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.2.2'),
  ('TIER_3', 'GENERAL_EDUCATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'GENERAL_EDUCATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.1.3'),
  ('TIER_4', 'GENERAL_EDUCATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.2.2'),
  ('TIER_4', 'GENERAL_EDUCATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'GENERAL_EDUCATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'GENERAL_EDUCATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'GENERAL_EDUCATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_1', 'CLINICAL_EFFICACY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.6'),
  ('TIER_1', 'CLINICAL_EFFICACY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.6'),
  ('TIER_1', 'CLINICAL_EFFICACY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'CLINICAL_EFFICACY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.6'),
  ('TIER_2', 'CLINICAL_EFFICACY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.6'),
  ('TIER_2', 'CLINICAL_EFFICACY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'CLINICAL_EFFICACY', 'INFORMATIONAL', 'REQUIRES_CORROBORATION', NULL, 2, NULL, 'HP-ESC 1.3.7'),
  ('TIER_3', 'CLINICAL_EFFICACY', 'DECISION_SUPPORT', 'REQUIRES_CORROBORATION', NULL, 2, NULL, 'HP-ESC 1.3.7'),
  ('TIER_3', 'CLINICAL_EFFICACY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'CLINICAL_EFFICACY', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-SELF-REPORT', 'HP-ESC 1.4.4'),
  ('TIER_4', 'CLINICAL_EFFICACY', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-SELF-REPORT', 'HP-ESC 1.4.4'),
  ('TIER_4', 'CLINICAL_EFFICACY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'CLINICAL_EFFICACY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'CLINICAL_EFFICACY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'CLINICAL_EFFICACY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_1', 'TEST_INTERPRETATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_1', 'TEST_INTERPRETATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_1', 'TEST_INTERPRETATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_2', 'TEST_INTERPRETATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_2', 'TEST_INTERPRETATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_2', 'TEST_INTERPRETATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_3', 'TEST_INTERPRETATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_3', 'TEST_INTERPRETATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_3', 'TEST_INTERPRETATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_4', 'TEST_INTERPRETATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_4', 'TEST_INTERPRETATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_4', 'TEST_INTERPRETATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_5', 'TEST_INTERPRETATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_5', 'TEST_INTERPRETATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_5', 'TEST_INTERPRETATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.1.1'),
  ('TIER_1', 'REFERENCE_RANGE', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_1', 'REFERENCE_RANGE', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_1', 'REFERENCE_RANGE', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'REFERENCE_RANGE', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_2', 'REFERENCE_RANGE', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_2', 'REFERENCE_RANGE', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'REFERENCE_RANGE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_3', 'REFERENCE_RANGE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_3', 'REFERENCE_RANGE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_4', 'REFERENCE_RANGE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_4', 'REFERENCE_RANGE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_4', 'REFERENCE_RANGE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.5.1'),
  ('TIER_5', 'REFERENCE_RANGE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'REFERENCE_RANGE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'REFERENCE_RANGE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_1', 'ELIGIBILITY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_1', 'ELIGIBILITY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_1', 'ELIGIBILITY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'ELIGIBILITY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_2', 'ELIGIBILITY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_2', 'ELIGIBILITY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'ELIGIBILITY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_3', 'ELIGIBILITY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.2.6'),
  ('TIER_3', 'ELIGIBILITY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'ELIGIBILITY', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 3.2.6'),
  ('TIER_4', 'ELIGIBILITY', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 3.2.6'),
  ('TIER_4', 'ELIGIBILITY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'ELIGIBILITY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'ELIGIBILITY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'ELIGIBILITY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_1', 'COST', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_1', 'COST', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_1', 'COST', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'COST', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_2', 'COST', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_2', 'COST', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'COST', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_3', 'COST', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.3.1'),
  ('TIER_3', 'COST', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'COST', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.75, 1, 'HP-M-INDICATIVE-COST', 'HP-ESC 1.4.3 / 3.3.9'),
  ('TIER_4', 'COST', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.75, 1, 'HP-M-INDICATIVE-COST', 'HP-ESC 1.4.3 / 3.3.9'),
  ('TIER_4', 'COST', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'COST', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'COST', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'COST', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'PROVIDER_OUTCOME', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_1', 'PROVIDER_OUTCOME', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_1', 'PROVIDER_OUTCOME', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'PROVIDER_OUTCOME', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_2', 'PROVIDER_OUTCOME', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_2', 'PROVIDER_OUTCOME', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'PROVIDER_OUTCOME', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_3', 'PROVIDER_OUTCOME', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.1'),
  ('TIER_3', 'PROVIDER_OUTCOME', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'PROVIDER_OUTCOME', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-SELF-REPORT', 'HP-ESC 1.4.4'),
  ('TIER_4', 'PROVIDER_OUTCOME', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-SELF-REPORT', 'HP-ESC 1.4.4'),
  ('TIER_4', 'PROVIDER_OUTCOME', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'PROVIDER_OUTCOME', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'PROVIDER_OUTCOME', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'PROVIDER_OUTCOME', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'PROVIDER_CREDENTIAL', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_1', 'PROVIDER_CREDENTIAL', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_1', 'PROVIDER_CREDENTIAL', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'PROVIDER_CREDENTIAL', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_2', 'PROVIDER_CREDENTIAL', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_2', 'PROVIDER_CREDENTIAL', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'PROVIDER_CREDENTIAL', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_3', 'PROVIDER_CREDENTIAL', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.4.4'),
  ('TIER_3', 'PROVIDER_CREDENTIAL', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'PROVIDER_CREDENTIAL', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 3.4.3'),
  ('TIER_4', 'PROVIDER_CREDENTIAL', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 3.4.3'),
  ('TIER_4', 'PROVIDER_CREDENTIAL', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'PROVIDER_CREDENTIAL', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'PROVIDER_CREDENTIAL', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'PROVIDER_CREDENTIAL', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'GUIDELINE', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_1', 'GUIDELINE', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_1', 'GUIDELINE', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'GUIDELINE', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_2', 'GUIDELINE', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_2', 'GUIDELINE', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'GUIDELINE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.6.7 / 1.7 M6'),
  ('TIER_3', 'GUIDELINE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.6.7 / 1.7 M6'),
  ('TIER_3', 'GUIDELINE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'GUIDELINE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_4', 'GUIDELINE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.6.1'),
  ('TIER_4', 'GUIDELINE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'GUIDELINE', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'GUIDELINE', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'GUIDELINE', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_1', 'LEGAL_REGULATORY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_1', 'LEGAL_REGULATORY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_1', 'LEGAL_REGULATORY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_2', 'LEGAL_REGULATORY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_2', 'LEGAL_REGULATORY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_2', 'LEGAL_REGULATORY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_3', 'LEGAL_REGULATORY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_3', 'LEGAL_REGULATORY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_3', 'LEGAL_REGULATORY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_4', 'LEGAL_REGULATORY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_4', 'LEGAL_REGULATORY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_4', 'LEGAL_REGULATORY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_5', 'LEGAL_REGULATORY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'LEGAL_REGULATORY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'LEGAL_REGULATORY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.7.1'),
  ('TIER_1', 'LOGISTICS', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_1', 'LOGISTICS', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_1', 'LOGISTICS', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'LOGISTICS', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_2', 'LOGISTICS', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_2', 'LOGISTICS', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'LOGISTICS', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_3', 'LOGISTICS', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_3', 'LOGISTICS', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'LOGISTICS', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_4', 'LOGISTICS', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_4', 'LOGISTICS', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'LOGISTICS', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_5', 'LOGISTICS', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.4'),
  ('TIER_5', 'LOGISTICS', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'SENTIMENT', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_1', 'SENTIMENT', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_1', 'SENTIMENT', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'SENTIMENT', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_2', 'SENTIMENT', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_2', 'SENTIMENT', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'SENTIMENT', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_3', 'SENTIMENT', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.5'),
  ('TIER_3', 'SENTIMENT', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'SENTIMENT', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.4.5'),
  ('TIER_4', 'SENTIMENT', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 3.4.5'),
  ('TIER_4', 'SENTIMENT', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'SENTIMENT', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.4 / 1.5.5'),
  ('TIER_5', 'SENTIMENT', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.4, 1, 'HP-M-OPINION', 'HP-ESC 1.5.4 / 1.5.5'),
  ('TIER_5', 'SENTIMENT', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'MEDICATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_1', 'MEDICATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_1', 'MEDICATION', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'MEDICATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_2', 'MEDICATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_2', 'MEDICATION', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'MEDICATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.2 / HP-ESC 3.12.2'),
  ('TIER_3', 'MEDICATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.2 / HP-ESC 3.12.2'),
  ('TIER_3', 'MEDICATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'MEDICATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_4', 'MEDICATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_4', 'MEDICATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'MEDICATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'MEDICATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'MEDICATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_1', 'ACCREDITATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_1', 'ACCREDITATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_1', 'ACCREDITATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_2', 'ACCREDITATION', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_2', 'ACCREDITATION', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_2', 'ACCREDITATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_3', 'ACCREDITATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_3', 'ACCREDITATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.2.6'),
  ('TIER_3', 'ACCREDITATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_4', 'ACCREDITATION', 'INFORMATIONAL', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 1.2.6 / 3.4.3'),
  ('TIER_4', 'ACCREDITATION', 'DECISION_SUPPORT', 'PERMITTED_ATTRIBUTED', 0.55, 1, 'HP-M-CLAIMED-NOT-VERIFIED', 'HP-ESC 1.2.6 / 3.4.3'),
  ('TIER_4', 'ACCREDITATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_5', 'ACCREDITATION', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'ACCREDITATION', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'ACCREDITATION', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.1'),
  ('TIER_1', 'EPIDEMIOLOGY', 'INFORMATIONAL', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.7.1'),
  ('TIER_1', 'EPIDEMIOLOGY', 'DECISION_SUPPORT', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 1.7.1'),
  ('TIER_1', 'EPIDEMIOLOGY', 'CLINICAL_DECISION', 'PERMITTED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_2', 'EPIDEMIOLOGY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.3'),
  ('TIER_2', 'EPIDEMIOLOGY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.3'),
  ('TIER_2', 'EPIDEMIOLOGY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_3', 'EPIDEMIOLOGY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.3'),
  ('TIER_3', 'EPIDEMIOLOGY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ADR-003 §1.3'),
  ('TIER_3', 'EPIDEMIOLOGY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_4', 'EPIDEMIOLOGY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.4.4'),
  ('TIER_4', 'EPIDEMIOLOGY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.4.4'),
  ('TIER_4', 'EPIDEMIOLOGY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3'),
  ('TIER_5', 'EPIDEMIOLOGY', 'INFORMATIONAL', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'EPIDEMIOLOGY', 'DECISION_SUPPORT', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 1.5.3'),
  ('TIER_5', 'EPIDEMIOLOGY', 'CLINICAL_DECISION', 'PROHIBITED', NULL, 1, NULL, 'HP-ESC 2.3.3')
) AS v(tier, kind, category, disposition, confidence_cap, min_sources, marker_id,
       charter_clause);

-- §1.4.4 reconciliation: every attribute the registry marks marker-required must resolve
-- to at least one policy row that actually carries a marker. Run in CI; a violation means
-- the mandatory string will silently not be rendered.
CREATE OR REPLACE FUNCTION evidence.assert_marker_coverage()
RETURNS TABLE (entity_type text, attribute text, expected_claim_kind claim_kind)
LANGUAGE sql STABLE AS $$
  SELECT k.entity_type, k.attribute, k.expected_claim_kind
    FROM evidence.domain_attribute_kind k
   WHERE k.requires_marker
     AND NOT EXISTS (
       SELECT 1 FROM evidence.claim_policy p
        WHERE p.kind = k.expected_claim_kind
          AND p.marker_id IS NOT NULL);
$$;
